server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shitongtong/spring-cloud-microservice-study
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/